export const columns = [
  { field: "id", headerName: "Sl.No", width: 80, align: "center" },
  { field: "floor", headerName: "Floor", flex: 1, headerAlign: "center" },
  { field: "roomNumber", headerName: "Room Number", flex: 1, headerAlign: "center", align: "center" },
  { field: "type", headerName: "Type", flex: 1, headerAlign: "center" },
  { field: "space1", headerName: "", flex: 1, headerAlign: "center", align: "center" },
  { field: "rateEntry", headerName: "Rate Entry", flex: 1 },
  { field: "rateType", headerName: "Rate Type", flex: 2 },
];

export const rows = [
  { id: 1, floor: "Ground Floor", roomNumber: "G01", type: "Studio King", space1: "", rateEntry: "", rateType: "" },
  { id: 2, floor: "Ground Floor", roomNumber: "G02", type: "Studio King", space1: "10", rateEntry: "Studio King", rateType: "DG Rate" },
  { id: 3, floor: "First Floor", roomNumber: "101", type: "Studio King", space1: "", rateEntry: "", rateType: "DGB Rate" },
  { id: 4, floor: "First Floor", roomNumber: "102", type: "Studio Large", space1: "", rateEntry: "", rateType: "" },
  { id: 5, floor: "First Floor", roomNumber: "103", type: "Studio Large", space1: "4", rateEntry: "Studio Twin", rateType: "DG Rate" },
  { id: 6, floor: "First Floor", roomNumber: "104", type: "Studio King", space1: "", rateEntry: "", rateType: "DGB Rate" },
  { id: 7, floor: "First Floor", roomNumber: "105", type: "Suite Room", space1: "", rateEntry: "", rateType: "" },
  { id: 8, floor: "First Floor", roomNumber: "106", type: "Family Room", space1: "4", rateEntry: "Family Room", rateType: "DG Rate" },
  { id: 9, floor: "Second Floor", roomNumber: "201", type: "Studio King", space1: "", rateEntry: "", rateType: "DGB Rate" },
  { id: 10, floor: "Second Floor", roomNumber: "202", type: "Studio Large", space1: "", rateEntry: "", rateType: "" },
  { id: 11, floor: "Second Floor", roomNumber: "203", type: "Studio Large", space1: "4", rateEntry: "Suite Room", rateType: "DG Rate" },
  { id: 12, floor: "Second Floor", roomNumber: "204", type: "Studio King", space1: "", rateEntry: "", rateType: "DGB Rate" },
  { id: 13, floor: "Second Floor", roomNumber: "205", type: "Suite Room", space1: "", rateEntry: "", rateType: "" },
  { id: 14, floor: "Second Floor", roomNumber: "206", type: "Family Room", space1: "4", rateEntry: "Studio Large", rateType: "DG Rate" },
  { id: 15, floor: "Third Floor", roomNumber: "301", type: "Studio King", space1: "", rateEntry: "", rateType: "DGB Rate" },
  { id: 16, floor: "Third Floor", roomNumber: "302", type: "Studio Twin", space1: "", rateEntry: "", rateType: "" },
  { id: 17, floor: "Third Floor", roomNumber: "303", type: "Studio Twin", space1: "1", rateEntry: "VIP", rateType: "DG Rate" },
  { id: 18, floor: "Third Floor", roomNumber: "304", type: "Studio King", space1: "", rateEntry: "", rateType: "DGB Rate" },
  { id: 19, floor: "Third Floor", roomNumber: "305", type: "Suite Room", space1: "", rateEntry: "", rateType: "" },
  { id: 20, floor: "Third Floor", roomNumber: "306", type: "Family Room", space1: "4", rateEntry: "Single Bed", rateType: "DG Rate" },
  { id: 21, floor: "Forth Floor", roomNumber: "401", type: "Studio King", space1: "", rateEntry: "", rateType: "DGB Rate" },
  { id: 22, floor: "Forth Floor", roomNumber: "402", type: "Studio Twin", space1: "", rateEntry: "", rateType: "" },
  { id: 23, floor: "Forth Floor", roomNumber: "403", type: "Studio Twin", space1: "", rateEntry: "", rateType: "" },
  { id: 24, floor: "Forth Floor", roomNumber: "404", type: "Studio King", space1: "31", rateEntry: "31", rateType: "" },
  { id: 25, floor: "Forth Floor", roomNumber: "405", type: "Suite Room", space1: "", rateEntry: "", rateType: "" },
  { id: 26, floor: "Forth Floor", roomNumber: "406", type: "Family Room", space1: "", rateEntry: "", rateType: "" },
  { id: 27, floor: "Fifth Floor", roomNumber: "501", type: "VIP", space1: "", rateEntry: "", rateType: "" },
  { id: 28, floor: "Fifth Floor", roomNumber: "502", type: "Single Bed", space1: "", rateEntry: "", rateType: "" },
  { id: 29, floor: "Fifth Floor", roomNumber: "503", type: "Single Bed", space1: "", rateEntry: "", rateType: "" },
  { id: 30, floor: "Fifth Floor", roomNumber: "504", type: "Single Bed", space1: "", rateEntry: "", rateType: "" },
  { id: 31, floor: "Fifth Floor", roomNumber: "505", type: "Single Bed", space1: "", rateEntry: "", rateType: "" },
];